[US-624] Create Letter with Header form Template
unidoc/unioffice-examples pull request #37
Opened 2024-09-25 18:17 UTC by kellemNegasi

2024-09-25 20:35 UTC, sampila requested changes
Overall looks good, added minor comments

2024-09-25 20:35 UTC, sampila commented on document/template-with-header/main.go
> +		log.Fatalf("error opening Windows Word 2016 document: %s", err)
Probably just write
```
log.Fatalf("error opening file: %s", err)
```

2024-09-25 20:35 UTC, sampila commented on document/template-with-header/main.go
> +	// }
Probably here can take "Normal" style and put into variable, so later can use that to set the style.

2024-09-26 05:21 UTC, anovik commented on document/template-with-header/main.go
> +		panic(err)
Maybe instead of panic - log error and return?

2024-09-26 05:22 UTC, anovik commented on document/template-with-header/main.go
> +		generateDoc("letter_template.docx", letter, fmt.Sprintf("./output/letter_to_%s.docx", letter.Receiver))
should we proceed possible error from generateDoc?

2024-09-26 05:23 UTC, anovik commented on document/template-with-header/main.go
> +// Copyright 2017 FoxyUtils ehf. All rights reserved.
probably update year in copyright?

2024-09-26 14:32 UTC, anovik approved these changes

2024-09-26 15:48 UTC, sampila requested changes
added comments

2024-09-26 15:48 UTC, sampila commented on document/template-with-header/main.go
> +	var Normal string // style for the body of the letter
probably should be
```
var styleNormal string
```

2024-09-26 15:48 UTC, sampila commented on document/template-with-header/main.go
> +		// fmt.Println("style", s.Name(), "has ID of", s.StyleID(), "type is", s.Type())
better to remove this and changes to 
```
Look for style named "normal" from document styles.
for _, s := range templateDoc.Styles.Styles() {
 ...
}
```

And later can remove the comments of
```
// style name taken from the doc.Styles.Styles() list
```

2024-09-26 16:00 UTC, sampila approved these changes
Looks good to me

2024-09-26 16:00 UTC, merged