[US-628] UniOffice Api Usage Example
unidoc/unioffice-examples pull request #38
Opened 2024-09-26 15:23 UTC by kellemNegasi

2024-09-26 16:03 UTC, sampila requested changes
added a comment

2024-09-26 16:03 UTC, sampila commented on license/usage-logs/main.go
> +	}
Probably can make a simple operation for this example?
like open and then modify docx, so we can remove this code and we also already had convert to pdf example.

2024-09-26 16:07 UTC, sampila reviewed
added a comment

2024-09-26 16:07 UTC, sampila commented on license/usage-logs/README.md
> +When Using unioffice it is possible to see the usage logs of license key in every run. To enable this behavior all we have to do is setting the `UsageLog` to verbose and the log level to `Info` or ab
Probably also mention that this only available for api key based license(metered api key)

2024-09-26 19:21 UTC, sampila commented on license/usage-logs/README.md
> +When using unioffice on metered api key it is possible to see the usage logs of license key in every run. To enable this behavior all we have to do is setting the `UsageLog` to verbose and the log le
... To enable this set the `license.SetMeteredKeyUsageLogVerboseMode` to `true` and to print out into console set the `logger.SetLogger` to `Info` or higher.

2024-09-26 19:22 UTC, sampila commented on license/usage-logs/main.go
> +	// Enable the verbose mode logging
// Enable the usage log verbose mode to log the usages info

2024-09-27 12:30 UTC, kellemNegasi commented
@sampila can you check again.

2024-09-27 13:33 UTC, sampila approved these changes
Looks good to me

2024-09-27 13:33 UTC, merged